spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yjmyzz/spring-cloud-config-repository
#          username: ***
#          password: ***


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
